parameters:
 - name: targetPath 
   type: string 
   default: ''

steps:

    - checkout: self
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: ${{ parameters.targetPath }}
        artifact: 'Drop'
        publishLocation: 'pipeline'