parameters:
 - name: workingDirectory 
   type: string 
   default: ''
 - name: workspaceName
   type: string 
   default: ''
 - name: varFilePlan
   type: string 
   default: ''
 - name: servicePrincipal
   type: string
   default: ''
 - name: stateFileSub
   type: string
   default: ''
 - name: stateFileRG
   type: string
   default: ''
 - name: stateFileAccount
   type: string
   default: ''
 - name: stateFileContainer
   type: string
   default: ''

steps:
      - checkout: none
      - download: current
        artifact: Drop

      - task: TerraformTaskV2@2
        displayName: 'Terraform Init'
        inputs:
          backendType: 'azurerm'
          command: 'init'
          workingDirectory:                 ${{ parameters.workingDirectory }}
          backendServiceArm:                ${{ parameters.servicePrincipal }}
          backendAzureRmSubscriptionId:     ${{ parameters.stateFileSub }}
          backendAzureRmResourceGroupName:  ${{ parameters.stateFileRG }}
          backendAzureRmStorageAccountName: ${{ parameters.stateFileAccount }}
          backendAzureRmContainerName:      ${{ parameters.stateFileContainer }}
          backendAzureRmKey:                'terraform.tfstate'

      - template: ../steps/workspace-template.yaml
        parameters:
           workspaceName:                 ${{ parameters.workspaceName }}
           workingDirectory:              ${{ parameters.workingDirectory }}

      - task: TerraformTaskV2@2
        displayName: 'Terraform Validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory:               ${{ parameters.workingDirectory }}

      - template: ../steps/plan-template.yaml
        parameters:
           workingDirectory:              ${{ parameters.workingDirectory }}
           varFilePlan:                   ${{ parameters.varFilePlan }}
           servicePrincipal:              ${{ parameters.servicePrincipal }}