parameters:
- name: MicroServiceName
  type: string
  default: ''

- name: gradletasks
  type: string
  default: 'sonar'

stages:
- stage: CodeAnalysis
  displayName: "Code Analysis"
  pool: 'Gaskit'
  variables:
    - group: Gaskit-API-SonarQube
  jobs:
  - job:
    steps:
      - task: Gradle@3
        displayName: 'Run Sonar Tasks'
        inputs:
          gradleWrapperFile: '$(Build.SourcesDirectory)/${{ parameters.MicroServiceName }}/gradlew'
          workingDirectory: '$(Build.SourcesDirectory)/${{ parameters.MicroServiceName }}'
          options: '-Dsonar.projectKey=${{ parameters.MicroServiceName }} -Dsonar.host.url=$(Gaskit.SonarQube.Configuration.SonarHost) -Dsonar.token=$(Gaskit.SonarQube.Configuration.SonarLoginKey) --gradle-user-home=$(Build.SourcesDirectory)/${{ parameters.MicroServiceName }}'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'Path'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          jdkDirectory: '/usr/lib/jvm/java-11-amazon-corretto'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: '${{ parameters.gradletasks }}'
