steps:
- task: Bash@3
  displayName: Dump all Environment variables 
  inputs:
          targetType: 'inline'
          script: 'env | sort'
          
- download: none

- task: DownloadPipelineArtifact@2
  inputs:
    artifactName: 'API-Artifacts'

- bash: |
    docker build -t $(acrserver)/sample-api:$(Build.BuildNumber) .
  workingDirectory: $(Pipeline.Workspace)
  displayName: 'Docker Build'
      
- script: |
      docker login $(acrserver) --username $(DockerUsername) --password $(DockerPassword)
      docker push $(acrserver)/sample-api:$(Build.BuildNumber)
  workingDirectory: $(Pipeline.Workspace)
  displayName: 'Docker Push'

- script: |
    sudo docker rmi -f $(acrserver)/sample-api:$(Build.BuildNumber)
  displayName: "Post Build Docker Cleanup"
  continueOnError: true
  condition: always()